version: "3.8"

services:
  redis:
    image: redis/redis-stack-server:latest
    restart: always
    command: redis-server
    environment:
      - REDIS_USER=user
      - REDIS_PASSWORD=password
    ports:
      - 6379:6379
    volumes:
      - ./docker-data/db:/var/lib/redis/data
